version: "3.9"
services:
  neo4j:
    image: neo4j:5.14
    container_name: ea_neo4j
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/pass1234
      - NEO4J_PLUGINS=["graph-data-science"]
    ports:
      - "7474:7474"  # Browser UI
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data

  backend:
    build: .
    container_name: ea_backend
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=pass1234
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENV=${PINECONE_ENV}
      - PINECONE_INDEX=capstone-demo
    depends_on:
      - neo4j
    ports:
      - "8000:8000"

volumes:
  neo4j_data:
