version: '3.8'
services:
  neo4j:
    image: neo4j:5.14
    container_name: graph_rag_neo4j
    environment:
      - NEO4J_AUTH=neo4j/pass1234
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["graph-data-science"]
    ports:
      - 7474:7474  # Browser
      - 7687:7687  # Bolt
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
